spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products-api
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
